//
//  ExportService.swift
//  DevSketch
//
//  Handles Flutter project generation and export
//  Creates complete project structure ready to run
//

import Foundation
import UIKit
// import ZIPFoundation // TODO: Add ZIPFoundation package dependency

// MARK: - Export Service

class ExportService {

    // MARK: - Properties

    private let fileManager = FileManager.default
    private let tempDirectory: URL

    // MARK: - Templates

    private let pubspecTemplate = """
name: {{PROJECT_NAME}}
description: Flutter app generated by DevSketch Mobile - Sketch to code in seconds.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Generated by DevSketch Mobile
# https://github.com/Kevthetech143/arm-devsketch-mobile
# Powered by Arm AI
"""

    private let mainTemplate = """
import 'package:flutter/material.dart';
import 'generated_page.dart';

void main() {
  runApp(const DevSketchApp());
}

class DevSketchApp extends StatelessWidget {
  const DevSketchApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '{{PROJECT_NAME}}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(
              horizontal: 24,
              vertical: 12,
            ),
          ),
        ),
      ),
      darkTheme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
      ),
      themeMode: ThemeMode.system,
      home: const GeneratedPage(),
    );
  }
}

// Generated by DevSketch Mobile
// Powered by Arm AI
"""

    private let readmeTemplate = """
# {{PROJECT_NAME}}

Flutter app generated by **DevSketch Mobile** - Sketch to code in seconds.

## Getting Started

```bash
flutter pub get
flutter run
```

## Project Structure

```
lib/
├── main.dart          # App entry point
└── generated_page.dart # Generated UI from sketch
```

## Customization

- Edit `generated_page.dart` to modify the UI
- Update theme in `main.dart`
- Add navigation, state management as needed

---

**Generated by DevSketch Mobile**
https://github.com/Kevthetech143/arm-devsketch-mobile

*100% on-device AI - Powered by Arm Neural Engine*
"""

    private let analysisOptionsTemplate = """
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
"""

    private let gitignoreTemplate = """
# Flutter/Dart
.dart_tool/
.packages
build/
.pub/

# iOS/Android
ios/Pods/
android/.gradle/

# IDE
.idea/
*.iml
.vscode/

# Generated
*.g.dart
"""

    // MARK: - Initialization

    init() {
        tempDirectory = fileManager.temporaryDirectory.appendingPathComponent("DevSketchExport")
    }

    // MARK: - Public Methods

    /// Generate complete Flutter project structure
    func createFlutterProject(name: String, code: String) -> URL? {
        let projectName = sanitizeProjectName(name)
        let projectURL = tempDirectory.appendingPathComponent(projectName)

        do {
            // Clean up any existing project
            if fileManager.fileExists(atPath: projectURL.path) {
                try fileManager.removeItem(at: projectURL)
            }

            // Create project directory structure
            try createProjectStructure(at: projectURL, name: projectName, code: code)

            return projectURL

        } catch {
            print("Error creating Flutter project: \(error)")
            return nil
        }
    }

    /// Create ZIP archive for sharing
    func createZipArchive(projectURL: URL) -> URL? {
        // TODO: Implement ZIP archive creation with ZIPFoundation package
        print("ZIP archive creation not yet implemented - add ZIPFoundation dependency")
        return nil

        // Uncomment when ZIPFoundation is added:
        /*
        let zipURL = tempDirectory.appendingPathComponent("\(projectURL.lastPathComponent).zip")

        do {
            // Remove existing ZIP if present
            if fileManager.fileExists(atPath: zipURL.path) {
                try fileManager.removeItem(at: zipURL)
            }

            // Create ZIP archive
            try fileManager.zipItem(at: projectURL, to: zipURL)

            return zipURL

        } catch {
            print("Error creating ZIP archive: \(error)")
            return nil
        }
        */
    }

    /// Share via UIActivityViewController
    func shareProject(zipURL: URL, from viewController: UIViewController) {
        let activityController = UIActivityViewController(
            activityItems: [zipURL],
            applicationActivities: nil
        )

        // iPad support
        if let popover = activityController.popoverPresentationController {
            popover.sourceView = viewController.view
            popover.sourceRect = CGRect(
                x: viewController.view.bounds.midX,
                y: viewController.view.bounds.midY,
                width: 0,
                height: 0
            )
        }

        viewController.present(activityController, animated: true)
    }

    /// Export code to clipboard
    func copyCodeToClipboard(_ code: String) {
        UIPasteboard.general.string = code
    }

    /// Quick share just the generated code
    func shareCode(_ code: String, from viewController: UIViewController) {
        let activityController = UIActivityViewController(
            activityItems: [code],
            applicationActivities: nil
        )

        if let popover = activityController.popoverPresentationController {
            popover.sourceView = viewController.view
            popover.sourceRect = CGRect(
                x: viewController.view.bounds.midX,
                y: viewController.view.bounds.midY,
                width: 0,
                height: 0
            )
        }

        viewController.present(activityController, animated: true)
    }

    // MARK: - Private Methods

    private func sanitizeProjectName(_ name: String) -> String {
        let sanitized = name
            .lowercased()
            .replacingOccurrences(of: " ", with: "_")
            .replacingOccurrences(of: "-", with: "_")
            .filter { $0.isLetter || $0.isNumber || $0 == "_" }

        return sanitized.isEmpty ? "devsketch_app" : sanitized
    }

    private func createProjectStructure(at projectURL: URL, name: String, code: String) throws {
        // Create directories
        let libDir = projectURL.appendingPathComponent("lib")
        let androidDir = projectURL.appendingPathComponent("android")
        let iosDir = projectURL.appendingPathComponent("ios")
        let testDir = projectURL.appendingPathComponent("test")

        try fileManager.createDirectory(at: libDir, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: androidDir, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: iosDir, withIntermediateDirectories: true)
        try fileManager.createDirectory(at: testDir, withIntermediateDirectories: true)

        // Create pubspec.yaml
        let pubspecContent = pubspecTemplate.replacingOccurrences(of: "{{PROJECT_NAME}}", with: name)
        try pubspecContent.write(
            to: projectURL.appendingPathComponent("pubspec.yaml"),
            atomically: true,
            encoding: .utf8
        )

        // Create lib/main.dart
        let mainContent = mainTemplate.replacingOccurrences(of: "{{PROJECT_NAME}}", with: name)
        try mainContent.write(
            to: libDir.appendingPathComponent("main.dart"),
            atomically: true,
            encoding: .utf8
        )

        // Create lib/generated_page.dart (the AI-generated code)
        try code.write(
            to: libDir.appendingPathComponent("generated_page.dart"),
            atomically: true,
            encoding: .utf8
        )

        // Create README.md
        let readmeContent = readmeTemplate.replacingOccurrences(of: "{{PROJECT_NAME}}", with: name)
        try readmeContent.write(
            to: projectURL.appendingPathComponent("README.md"),
            atomically: true,
            encoding: .utf8
        )

        // Create analysis_options.yaml
        try analysisOptionsTemplate.write(
            to: projectURL.appendingPathComponent("analysis_options.yaml"),
            atomically: true,
            encoding: .utf8
        )

        // Create .gitignore
        try gitignoreTemplate.write(
            to: projectURL.appendingPathComponent(".gitignore"),
            atomically: true,
            encoding: .utf8
        )

        // Create minimal android stub
        try createAndroidStub(at: androidDir, name: name)

        // Create minimal ios stub
        try createIOSStub(at: iosDir, name: name)

        // Create test stub
        try createTestStub(at: testDir)
    }

    private func createAndroidStub(at androidDir: URL, name: String) throws {
        let buildGradle = """
        // Android build configuration stub
        // Run 'flutter create .' to generate full Android project

        // Project: \(name)
        // Generated by DevSketch Mobile
        """
        try buildGradle.write(
            to: androidDir.appendingPathComponent("README.md"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func createIOSStub(at iosDir: URL, name: String) throws {
        let iosReadme = """
        // iOS project configuration stub
        // Run 'flutter create .' to generate full iOS project

        // Project: \(name)
        // Generated by DevSketch Mobile
        """
        try iosReadme.write(
            to: iosDir.appendingPathComponent("README.md"),
            atomically: true,
            encoding: .utf8
        )
    }

    private func createTestStub(at testDir: URL) throws {
        let widgetTest = """
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Generated page renders', (WidgetTester tester) async {
    // TODO: Add widget tests
  });
}
"""
        try widgetTest.write(
            to: testDir.appendingPathComponent("widget_test.dart"),
            atomically: true,
            encoding: .utf8
        )
    }

    // MARK: - Cleanup

    func cleanupTempFiles() {
        try? fileManager.removeItem(at: tempDirectory)
    }
}

// MARK: - Export Result

struct ExportResult {
    let projectURL: URL?
    let zipURL: URL?
    let success: Bool
    let errorMessage: String?

    static func success(projectURL: URL, zipURL: URL) -> ExportResult {
        ExportResult(projectURL: projectURL, zipURL: zipURL, success: true, errorMessage: nil)
    }

    static func failure(_ message: String) -> ExportResult {
        ExportResult(projectURL: nil, zipURL: nil, success: false, errorMessage: message)
    }
}
